### ISSUE TITLE
improvement on dms performance

### ISSUE THREAD

**Issue by csacro** [Marco5de/Nachrichtentechnik#2]
use following code:

for i=1:length(seq)
    x = [x, repmat((i-1+'A'), 1, seq(i))];
end

**Comment by Marco5de** [comment]
kopiert das nicht immer noch?

**Comment by Marco5de** [comment]
Zwar weniger aber immernoch. Will eigentlich nur einen q+x langen Vektor und dann wird noch noch geschrieben
